"""created transactions and cryptocurrencies tables

Revision ID: c66c07c76bbe
Revises: 3988d4f0408f
Create Date: 2020-09-11 15:20:01.358241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66c07c76bbe'
down_revision = '3988d4f0408f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('crypto_amount', sa.Float(), nullable=False),
    sa.Column('usd_amount', sa.Float(), nullable=False),
    sa.Column('price_per_coin', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crypto_currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crypto_currency_id'], ['cryptocurrencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('cryptocurrencies')
    # ### end Alembic commands ###
